/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 4.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ProHealth.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'ProHealth.view.MainViewModel',
        'Ext.Container'
    ],

    viewModel: {
        type: 'main'
    },
    tabBarPosition: 'bottom',

    items: [
        {
            xtype: 'container',
            title: 'Search Doctor',
            html: 'Search Doctors'
        },
        {
            xtype: 'container',
            title: 'Records',
            html: 'Records'
        },
        {
            xtype: 'container',
            title: 'Schedule',
            html: 'Schedule'
        },
        {
            xtype: 'container',
            title: 'Profile',
            html: 'Profile'
        }
    ]

});